name: "Reusable SonarQube Scan"

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
      project-name:
        required: true
        type: string
      scan-dir:
        required: false
        type: string
        default: "."
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: false

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL || 'https://sonarcloud.io' }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.project-key }}
            -Dsonar.projectName=${{ inputs.project-name }}
            -Dsonar.sources=${{ inputs.scan-dir }}
